export const domains = [
  "Agriculture,FoodTech and Rural Development",
  "Blockchain and Cybersecurity",
  "Clean and Green Technology",
  "Fitness and Sports",
  "Heritage and Culture",
  "MedTech / BioTech / HealthTech",
  "Renewable / Sustainable Energy",
  "Robotics and Drones",
  "Smart Automation",
  "Smart Vehicles",
  "Travel and Tourism",
  "Transportation and Logistics",
  "Disaster Management",
  "Smart Education",
  "Image Processing",
  "Embedded Systems",
  "Networking",
  "Miscellaneous",
];
